[build]
  publish = "public"
  command = "./build.sh"

[build.environment]
  HUGO_VERSION = "0.120.0"
  HUGO_ENV = "production"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
